[tool.poetry]
name = "tarq"
version = "0.1.1"
description = "A Python TA library build with rust"
authors = ["Sigurd Lund <siglun@gmail.com>"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.poetry.dependencies]
python = ">=3.10"