name: Build and Upload Wheels

on:
  push:
    tags:
      - 'v*'  # Run only when a version tag (e.g., v1.0.0) is pushed
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build wheels
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64, aarch64]
        exclude:
          - os: windows-latest
            target: aarch64  # Windows does not support aarch64 cross-compilation

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Maturin
        uses: messense/maturin-action@v1
        with:
          target: ${{ matrix.target }}

      # --- Linux: Build Manylinux Wheels ---
      - name: Build Linux Wheels (manylinux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          maturin build --release --out dist --manylinux 2014 --target ${{ matrix.target }}

      # --- macOS: Build Universal2 Wheels ---
      - name: Build macOS Wheels (universal2)
        if: matrix.os == 'macos-latest'
        run: |
          maturin build --release --out dist --universal2

      # --- Windows: Build Wheels ---
      - name: Build Windows Wheels
        if: matrix.os == 'windows-latest'
        run: |
          maturin build --release --out dist

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.target }}
          path: dist/*.whl

  upload:
    name: Upload to GitHub Releases
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
